services:
  - type: web
    name: real-estate-api
    env: node
    plan: free
    rootDir: renderruncommands
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
